import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/sharedlayout/nav";
import Footer from "@/sharedlayout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" pt-2 flex flex-col ">
        <div className="w-full">
          <Nav />
          <div className="mt-0 w-full">{children}</div>
        </div>
        <Footer/>
      </body>
    </html>
  );
}
