import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '@/sharedlayout/nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='px-10 pt-2 flex flex-col '>
        <div className='hero-banner'>
          
        <Nav/>
        {children}
        
        </div>
        </body>
    </html>
  )
}
